// Code generated by gogenlicense at {{ fdate .Time "02-01-2006 15:04:05" }}; DO NOT EDIT.

// spellchecker: words gogenlicense
// spellchecker: disable

package {{ .Options.OutPackage }}


{{ prefix .DocString "// " }}
const {{ .Options.DeclarationName }} = {{ .NoticeString | printf "%q" }}
