// Code generated by gogenlicense; DO NOT EDIT.

// spellchecker: words gogenlicense
// spellchecker: disable

package {{ .Options.OutPackage }}


{{ prefix .DocString "// " }}
const {{ .Options.DeclarationName }} = {{ .NoticeString | printf "%q" }}
