// Code generated by gogenlicense at {{ fdate .Time "02-01-2006 15:04:05" }}; DO NOT EDIT.

// spellchecker: words gogenlicense
// spellchecker: disable

package {{ .Options.OutPackage }}


{{ prefix .DocString "// " }}
var {{ .Options.DeclarationName }} string

func init() {
	{{ .Options.DeclarationName }} = {{ .NoticeString | printf "%q" }}
}
